import Head from 'next/head';
import CardList from '../Components/Card/CardList';
import Container from '../Components/Layout/Container';
import useSWR from 'swr';
import { News } from '../types/newstypes';

const fetcher = async () => {
  const response = await fetch(
    `https://s3-ap-southeast-1.amazonaws.com/he-public-data/gamesarena274f2bf.json`
  );
  const data = await response.json();
  return data.slice(1);
};
const Home: React.ReactNode = () => {
  const { data, error } = useSWR(`homepage`, fetcher);
  if (error) return `Something Went Wrong`;
  if (!data) return `Loading`;

  return (
    <Container>
      <Head>
        <title>News feed GGWP</title>
        <meta name="description" content="Generated by News feed GGWP" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        {data.map(({ title, platform, score, genre, editors_choice }: News) => (
          <CardList
            key={title}
            title={title}
            platform={platform}
            score={score}
            genre={genre}
            editors_choice={editors_choice}
          />
        ))}
      </div>
    </Container>
  );
};

export default Home;
